version: '3'

services:
  cbioportal:
    restart: unless-stopped
    image: ghcr.io/buschlab/cbioportal:${RELEASE:-latest}
    build:
      context: services/cbioportal
    container_name: cbioportal_container
    environment:
      DB_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
      SHOW_DEBUG_INFO: "true"
    volumes:
     - ./study:/study/
     - ./config/portal.properties:/cbioportal/portal.properties:ro
     - ./config/client-tailored-saml-idp-metadata.xml:/cbioportal-webapp/WEB-INF/classes/client-tailored-saml-idp-metadata.xml
     - ./config/samlKeystore.jks:/cbioportal-webapp/WEB-INF/classes/samlKeystore.jks
     - ./config/frontend.json:/cbioportal/frontend.json:ro
    depends_on:
     - cbioportal_database
     - cbioportal_session
    ports:
      - "5005:5005"
      - "8081:8080"
    networks:
     - cbioportal_net
    command: [ 
      "/usr/bin/java",
      "-Xmx4g",
      "-Xdebug",
      "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005",
      "-Doncokb.public_api.url=${ONCOKB_URL:-https://public.api.oncokb.org/api/v1}",
      "-Doncokb.token=${ONCOKB_TOKEN}",
      "-Dgenomenexus.url=/genome-nexus",
      "-Dauthenticate=${AUTHENTICATE:-noauthsessionservice}",
      "-Dsession.service.url=http://cbioportal_session:5000/api/sessions/my_portal/",
      "-Dshow.civic=${ENABLE_CIVIC:-true}",
      "-Dmycancergenome.show=${ENABLE_MYCANCERGENOME:-false}",
      "-Dquick_search.enabled=${ENABLE_QUICKSEARCH:-true}",
      "-Dfilter_groups_by_appname=false",
      "-Dsaml.sp.metadata.entityid=cbioportal",
      "-Dsaml.sp.metadata.entitybaseurl=${CBIOPORTAL_URL}",
      "-Dsaml.idp.metadata.location=classpath:/client-tailored-saml-idp-metadata.xml",
      "-Dsaml.idp.metadata.entityid=${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}",
      "-Dsaml.keystore.location=classpath:/samlKeystore.jks",
      "-Dsaml.keystore.private-key.key=${KEYSTORE_KEY}",
      "-Dsaml.keystore.password=${KEYSTORE_PASSWORD}",
      "-Dsaml.keystore.default-key=${KEYSTORE_KEY}",
      "-Dsaml.keystore.private-key.password=${KEYSTORE_PASSWORD}",
      "-Dsaml.idp.metadata.attribute.email=email",
      "-Dsaml.idp.metadata.attribute.role=Role",
      "-Dsaml.custom.userservice.class=org.cbioportal.security.spring.authentication.keycloak.SAMLUserDetailsServiceImpl",
      "-Dhttps.proxyHost=${HTTPS_PROXY_HOST}",
      "-Dhttps.proxyPort=${HTTPS_PROXY_PORT}",
      "-Dfrontend.config=/cbioportal/frontend.json",
      "-jar",
      "/webapp-runner.jar",
      "-AmaxHttpHeaderSize=16384",
      "-AconnectionTimeout=20000",
      "--enable-compression",
      "/cbioportal-webapp"
    ]
  cbioportal_database:
    restart: unless-stopped
    image: mariadb:10.6.0
    container_name: cbioportal_database_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-P@ssword1}
      MYSQL_DATABASE: cbioportal
      MYSQL_USER: cbio
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./data/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:ro
     - ./data/seed-cbioportal_hg19_v2.7.3.sql.gz:/docker-entrypoint-initdb.d/seed.sql.gz:ro
     - cbioportal_data:/var/lib/mysql
    command:
     - --character-set-server=latin1
     - --collation-server=latin1_swedish_ci
    ports:
      - "3306:3306"
    networks:
     - cbioportal_net
  cbioportal_session:
    restart: unless-stopped
    image: cbioportal/session-service:0.4.0
    container_name: cbioportal_session_container
    environment:
      SERVER_PORT: 5000
      JAVA_OPTS: -Dspring.data.mongodb.uri=mongodb://cbioportal_session_database:27017/session-service
    depends_on:
      - cbioportal_session_database
    ports:
      - "5000:5000"
    networks:
      - cbioportal_net
  cbioportal_session_database:
    restart: unless-stopped
    image: mongo:3.7.9
    container_name: cbioportal_session_database_container
    environment:
      MONGO_INITDB_DATABASE: session_service
    volumes:
      - cbioportal_session_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - cbioportal_net
  fhirspark:
    restart: unless-stopped
    image: ghcr.io/buschlab/fhirspark:${RELEASE:-latest}
    build:
      context: services/fhirspark
    container_name: cbioportal_fhirspark
    depends_on:
      - hapiserver
    environment:
      FHIRSPARK_FHIRBASE: http://hapiserver:8080/fhir/
      FHIRSPARK_SENDHL7V2: ${HL7V2ENABLE:-false}
      FHIRSPARK_HL7V2SERVER: ${HL7V2SERVER}
      FHIRSPARK_HL7V2PORT: ${HL7V2PORT}
      FHIRSPARK_PORTALURL: http://cbioportal:8080/
      FHIRSPARK_LOGINREQUIRED: ${LOGINREQUIRED:-false}
    volumes:
      - ./data/drugs.json:/drugs.json:ro
      - ./data/hgnc.csv:/hgnc.csv:ro
    ports:
      - "3001:3001"
    networks:
      - cbioportal_net
  hapiserver:
    restart: unless-stopped
    image: hapiproject/hapi:v5.2.1
    container_name: cbioportal_fhirspark_hapiserver
    ports:
      - "8082:8080"
    depends_on:
      - hapi-postgres
    environment:
      hapi.fhir.server_address: "http://hapiserver:8080/fhir/"
      hapi.fhir.reuse_cached_search_results_millis: 5000
      hapi.fhir.implementationguides.genomics-reporting.name: hl7.fhir.uv.genomics-reporting
      hapi.fhir.implementationguides.genomics-reporting.version: 1.0.0
      hapi.fhir.validation.requests_enabled: 'false'
      spring.datasource.url: "jdbc:postgresql://hapi-postgres:5432/hapi?currentSchema=public"
      spring.datasource.username: hapiserver
      spring.datasource.password: ${POSTGRES_USER_PASSWORD:-P@ssword2}
      spring.datasource.driverClassName: org.postgresql.Driver
    networks:
      - cbioportal_net
  hapi-postgres:
    restart: unless-stopped
    image: postgres:12.6-alpine
    container_name: cbioportal_fhirspark_database
    volumes:
      - fhir_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hapiserver
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD:-P@ssword2}
      POSTGRES_DB: hapi
    ports:
      - "5432:5432"
    networks:
      - cbioportal_net
  nginx:
    restart: unless-stopped
    image: ghcr.io/buschlab/cbioproxy:${RELEASE:-latest}
    build:
      context: services/cbioproxy
    container_name: cbioportal_nginx_container
    volumes:
      - ./services/cbioproxy/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./services/cbioproxy/cbioportal.conf:/etc/nginx/conf.d/cbioportal.conf
      - ./services/cbioproxy/lua_auth_config.lua:/etc/nginx/conf.d/lua_auth_config.lua
      - ./services/cbioproxy/lua_login_config.lua:/etc/nginx/conf.d/lua_login_config.lua
    environment:
      NGINX_LOGINREQUIRED: ${LOGINREQUIRED:-true}
      KEYCLOAK_URL: ${KEYCLOAK_URL:-//localhost:8080}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-master}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT:-fhirspark}
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET:-nosecrethere}
      CBIOPORTAL_URL: ${CBIOPORTAL_URL:-//localhost:8080}
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - cbioportal
      - fhirspark
      - genomenexus
    networks:
      - cbioportal_net
  genomenexus:
    image: ghcr.io/buschlab/genome-nexus:${RELEASE:-latest}
    build:
      context: services/genome-nexus
    ports:
      - "8888:8888"
    environment:
      - SERVER_PORT=8888
    restart: unless-stopped
    depends_on:
      - genomenexus_db
      - ensembl-rest
      - ensembl-mysql
    command: [
      "-Dhttps.proxyHost=${HTTPS_PROXY_HOST}",
      "-Dhttps.proxyPort=${HTTPS_PROXY_PORT}",
      "-Dspring.data.mongodb.uri=mongodb://genomenexus_db:27017/annotator",
      "-Dvep.url=http://genomenexus_ensembl:3000/vep/human/hgvs/VARIANT?content-type=application/json&xref_refseq=1&ccds=1&canonical=1&domains=1&hgvs=1&numbers=1&protein=1",
      "-Dgenexrefs.url=http://genomenexus_ensembl:3000/xrefs/id/ACCESSION?content-type=application/json",
      "-jar",
      "/app/genome-nexus.war"
    ]
    networks:
      - cbioportal_net
  genomenexus_db:
    image: ghcr.io/buschlab/genome-nexus-db:${RELEASE:-latest}
    ports:
      - "27018:27017"
    volumes:
      - genomenexus_data:/bitnami/mongodb
    environment:
      - REF_ENSEMBL_VERSION=grch37_ensembl92
      - SPECIES=homo_sapiens
    restart: unless-stopped
    networks:
      - cbioportal_net
  ensembl-rest:
    image: nr205/ensembl-rest:${RELEASE:-latest}
    restart: unless-stopped
    ports:
      - "8083:3000"
    volumes:
      - ./config/ensembl_rest.conf:/opt/vep/src/ensembl-rest/ensembl_rest.conf
    networks:
      - cbioportal_net
    depends_on:
      - ensembl-mysql
  ensembl-mysql:
    image: ghcr.io/buschlab/ensembl-mysql:latest
    restart: unless-stopped
    networks:
      - cbioportal_net

networks:
  cbioportal_net: 
  
volumes:
  cbioportal_data:
  cbioportal_session_data:
  fhir_data:
  genomenexus_data:
