version: '3'

services:
  cbioportal:
    restart: unless-stopped
    image: cbioportal/cbioportal:3.6.6
    container_name: cbioportal_container
    environment:
      HTTP_PROXY: "http://${HTTPS_PROXY_HOST}:${HTTPS_PROXY_PORT}"
      NO_PROXY: "cbioportal,cbioportal_session"
      DB_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./study:/study/
     - ./config/portal.properties:/cbioportal/portal.properties:ro
     - ./config/client-tailored-saml-idp-metadata.xml:/cbioportal-webapp/WEB-INF/classes/client-tailored-saml-idp-metadata.xml
     - ./config/samlKeystore.jks:/cbioportal-webapp/WEB-INF/classes/samlKeystore.jks
     - ./config/${LOGO:-miracum.png}:/cbioportal-webapp/images/${LOGO:-miracum.png}
     - cbioportal_portalinfo:/cbioportal/portalinfo
    depends_on:
     - cbioportal_database
     - cbioportal_session
    networks:
     - cbioportal_net
    command: [ 
      "java",
      "-Xms2g",
      "-Xmx4g",
      "-Doncokb.public_api.url=${ONCOKB_URL:-https://public.api.oncokb.org/api/v1}",
      "-Doncokb.token=${ONCOKB_TOKEN}",
      "-Dgenomenexus.url=/genome-nexus",
      "-Dauthenticate=${AUTHENTICATE:-noauthsessionservice}",
      "-Dsession.service.url=http://cbioportal_session:5000/api/sessions/my_portal/",
      "-Dshow.civic=${ENABLE_CIVIC:-true}",
      "-Dmycancergenome.show=${ENABLE_MYCANCERGENOME:-true}",
      "-Dquick_search.enabled=${ENABLE_QUICKSEARCH:-true}",
      "-Dfilter_groups_by_appname=false",
      "-Dsaml.sp.metadata.entityid=cbioportal",
      "-Dsaml.sp.metadata.entitybaseurl=${CBIOPORTAL_URL}",
      "-Dsaml.idp.metadata.location=classpath:/client-tailored-saml-idp-metadata.xml",
      "-Dsaml.idp.metadata.entityid=${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}",
      "-Dsaml.keystore.location=classpath:/samlKeystore.jks",
      "-Dsaml.keystore.private-key.key=${KEYSTORE_KEY}",
      "-Dsaml.keystore.password=${KEYSTORE_PASSWORD}",
      "-Dsaml.keystore.default-key=${KEYSTORE_KEY}",
      "-Dsaml.keystore.private-key.password=${KEYSTORE_PASSWORD}",
      "-Dsaml.idp.metadata.attribute.email=email",
      "-Dsaml.idp.metadata.attribute.role=Role",
      "-Dsaml.custom.userservice.class=org.cbioportal.security.spring.authentication.keycloak.SAMLUserDetailsServiceImpl",
      "-Dhttps.proxyHost=${HTTPS_PROXY_HOST}",
      "-Dhttps.proxyPort=${HTTPS_PROXY_PORT}",
      "-Dskin.right_logo=${LOGO:-miracum.png}",
      "-jar",
      "/webapp-runner.jar",
      "-AmaxHttpHeaderSize=16384",
      "-AconnectionTimeout=20000",
      "--enable-compression",
      "--proxy-base-url",
      "${CBIOPORTAL_URL}",
      "/cbioportal-webapp"
    ]
  cbioportal_database:
    restart: unless-stopped
    image: mariadb:10.6.3
    container_name: cbioportal_database_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-P@ssword1}
      MYSQL_DATABASE: cbioportal
      MYSQL_USER: cbio
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./data/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:ro
     - ./data/seed-cbioportal_hg19_v2.12.8.sql.gz:/docker-entrypoint-initdb.d/seed.sql.gz:ro
     - cbioportal_data:/var/lib/mysql
    command:
     - --character-set-server=latin1
     - --collation-server=latin1_swedish_ci
    networks:
     - cbioportal_net
  cbioportal_session:
    restart: unless-stopped
    image: cbioportal/session-service:0.3.0
    container_name: cbioportal_session_container
    environment:
      SERVER_PORT: 5000
      JAVA_OPTS: -Dspring.data.mongodb.uri=mongodb://cbioportal_session_database:27017/session-service
    depends_on:
      - cbioportal_session_database
    networks:
      - cbioportal_net
  cbioportal_session_database:
    restart: unless-stopped
    image: mongo:3.7.9
    container_name: cbioportal_session_database_container
    environment:
      MONGO_INITDB_DATABASE: session_service
    volumes:
      - cbioportal_session_data:/data/db
    networks:
      - cbioportal_net
  nginx:
    restart: unless-stopped
    image: ghcr.io/buschlab/cbioproxy:${RELEASE:-latest}
    environment:
      NGINX_LOGINREQUIRED: ${LOGINREQUIRED:-false}
    container_name: cbioportal_nginx_container
    volumes:
      - ./services/cbioproxy/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./services/cbioproxy/cbioportal-research.conf:/etc/nginx/conf.d/cbioportal.conf
      - ./services/cbioproxy/lua_resource_config.lua:/etc/nginx/conf.d/lua_resource_config.lua
      - ./reports:/usr/share/reports
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - cbioportal
      - genomenexus
    networks:
      - cbioportal_net
  genomenexus:
    image: ghcr.io/buschlab/genome-nexus:${RELEASE:-latest}
    environment:
      - SERVER_PORT=8888
    restart: unless-stopped
    depends_on:
      - genomenexus_db
      - ensembl-rest
      - ensembl-mysql
    command: [
      "-Dhttps.proxyHost=${HTTPS_PROXY_HOST}",
      "-Dhttps.proxyPort=${HTTPS_PROXY_PORT}",
      "-Dspring.data.mongodb.uri=mongodb://genomenexus_db:27017/annotator",
      "-Dvep.url=http://ensembl-rest:3000/vep/human/hgvs/VARIANT?content-type=application/json&xref_refseq=1&ccds=1&canonical=1&domains=1&hgvs=1&numbers=1&protein=1",
      "-Dgenexrefs.url=http://ensembl-rest:3000/xrefs/id/ACCESSION?content-type=application/json",
      "-jar",
      "/app/genome-nexus.war"
    ]
    networks:
      - cbioportal_net
  genomenexus_db:
    image: ghcr.io/buschlab/genome-nexus-db:${RELEASE:-latest}
    volumes:
      - genomenexus_data:/bitnami/mongodb
    environment:
      - REF_ENSEMBL_VERSION=grch37_ensembl92
      - SPECIES=homo_sapiens
    restart: unless-stopped
    networks:
      - cbioportal_net
  ensembl-rest:
    image: nr205/ensembl-rest:${RELEASE:-latest}
    restart: unless-stopped
    volumes:
      - ./config/ensembl_rest.conf:/opt/vep/src/ensembl-rest/ensembl_rest.conf
    networks:
      - cbioportal_net
    depends_on:
      - ensembl-mysql
  ensembl-mysql:
    image: ghcr.io/buschlab/ensembl-mysql:latest
    restart: unless-stopped
    networks:
      - cbioportal_net

networks:
  cbioportal_net: 
  
volumes:
  cbioportal_data:
  cbioportal_session_data:
  cbioportal_portalinfo:
  genomenexus_data:
